# Generated by Django 5.0.6 on 2024-08-03 00:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupmessage",
            name="body",
            field=models.CharField(max_length=255),
        ),
    ]
